[project]
name = "myfastapiproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.118.0",
    "fastapi-cli>=0.0.13",
    "psycopg2>=2.9.10",
]
